version: '2'
services:
  nodered-app:
    extends:
      file: ./compose/app.yml
      service: app
    depends_on:
      - nodered-db
    links:
      - nodered-db:database

  nodered-db:
   extends:
      file: ./compose/db.yml
      service: db

  nodered-webpack:
    extends:
      file: ./compose/webpack.yml
      service: webpack
