version: '2'
services:
  db:
    container_name: nodered-db
    image: nodered-db:latest
    build: ../db/docker
    volumes:
      - /data:/data/db
      - ../.backup:/root/.backup
    ports:
      - 27017:27017
