version: '2'
services:
  webpack:
    container_name: nodered-webpack
    image: nodered-webpack:latest
    build: ../webpack/docker
    volumes:
      - ../nodered/app:/opt
      
    command: 'npm run build'
